
package Telas;

/**
 *
 * @author dayan
 */
public class menu_cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form menu_cadastrar
     */
    public menu_cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_menu = new javax.swing.JButton();
        bt_perfil = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_financeiro = new javax.swing.JButton();
        bt_aulas = new javax.swing.JButton();
        bt_adm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_prof = new javax.swing.JButton();
        bt_alunos = new javax.swing.JButton();
        bt_cadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_menu.setForeground(new java.awt.Color(255, 255, 255));
        bt_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/casa.png"))); // NOI18N
        bt_menu.setToolTipText("Menu");
        bt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menuActionPerformed(evt);
            }
        });
        jPanel1.add(bt_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 30, 30));

        bt_perfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_perfil.setForeground(new java.awt.Color(255, 255, 255));
        bt_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/do-utilizador.png"))); // NOI18N
        bt_perfil.setToolTipText("Perfil");
        jPanel1.add(bt_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 30));

        bt_sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_sair.setForeground(new java.awt.Color(255, 255, 255));
        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cartao-de-endereco.png"))); // NOI18N
        bt_sair.setToolTipText("Voltar");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        jPanel1.add(bt_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 30, 30));

        jPanel2.setBackground(new java.awt.Color(51, 81, 177));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.250x250.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -30, -1, -1));

        bt_financeiro.setBackground(new java.awt.Color(51, 81, 177));
        bt_financeiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_financeiro.setForeground(new java.awt.Color(255, 255, 255));
        bt_financeiro.setText("FINANCEIRO");
        bt_financeiro.setToolTipText("Clique para acessar opções sobre o financeiro");
        bt_financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_financeiroActionPerformed(evt);
            }
        });
        jPanel1.add(bt_financeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 160, 40));

        bt_aulas.setBackground(new java.awt.Color(51, 81, 177));
        bt_aulas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_aulas.setForeground(new java.awt.Color(255, 255, 255));
        bt_aulas.setText("AULAS");
        bt_aulas.setToolTipText("Clique para acessar opções sobre as aulas");
        bt_aulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aulasActionPerformed(evt);
            }
        });
        jPanel1.add(bt_aulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 160, 40));

        bt_adm.setBackground(new java.awt.Color(51, 140, 233));
        bt_adm.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        bt_adm.setForeground(new java.awt.Color(255, 255, 255));
        bt_adm.setText("ADMINISTRADORES");
        bt_adm.setToolTipText("Clique para cadastrar administradores");
        bt_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admActionPerformed(evt);
            }
        });
        jPanel1.add(bt_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aulas.80x57.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.80x57.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.80x57.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        bt_prof.setBackground(new java.awt.Color(51, 140, 233));
        bt_prof.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        bt_prof.setForeground(new java.awt.Color(255, 255, 255));
        bt_prof.setText("PROFESSORES");
        bt_prof.setToolTipText("Clique para cadastrar professores");
        bt_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_profActionPerformed(evt);
            }
        });
        jPanel1.add(bt_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 40));

        bt_alunos.setBackground(new java.awt.Color(51, 140, 233));
        bt_alunos.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        bt_alunos.setForeground(new java.awt.Color(255, 255, 255));
        bt_alunos.setText("ALUNOS");
        bt_alunos.setToolTipText("Clique para cadastrar alunos");
        bt_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alunosActionPerformed(evt);
            }
        });
        jPanel1.add(bt_alunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 40));

        bt_cadastro.setBackground(new java.awt.Color(51, 81, 177));
        bt_cadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        bt_cadastro.setText("CADASTRO");
        bt_cadastro.setToolTipText("Clique para cadastrar");
        bt_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_profActionPerformed
        Cadastro_professores menu = new Cadastro_professores();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_profActionPerformed

    private void bt_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alunosActionPerformed
        Cadastro_aluno menu = new Cadastro_aluno();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_alunosActionPerformed

    private void bt_admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admActionPerformed
        Cadastro_adm menu = new Cadastro_adm();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_admActionPerformed

    private void bt_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroActionPerformed
        Menu_inicial menu = new Menu_inicial();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_cadastroActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        Menu_inicial menu = new Menu_inicial();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menuActionPerformed
        Menu_inicial menu = new Menu_inicial();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_menuActionPerformed

    private void bt_aulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aulasActionPerformed
        menu_aula aula = new menu_aula();
        aula.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_aulasActionPerformed

    private void bt_financeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_financeiroActionPerformed
        menu_financeiro menu = new menu_financeiro();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_financeiroActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adm;
    private javax.swing.JButton bt_alunos;
    private javax.swing.JButton bt_aulas;
    private javax.swing.JButton bt_cadastro;
    private javax.swing.JButton bt_financeiro;
    private javax.swing.JButton bt_menu;
    private javax.swing.JButton bt_perfil;
    private javax.swing.JButton bt_prof;
    private javax.swing.JButton bt_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
